/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.imagsky.v7.biz;

import com.imagsky.dao.ContentFolderDAO;
import com.imagsky.util.CommonUtil;
import com.imagsky.util.JPAUtil;
import com.imagsky.util.logger.cmaLogger;
import com.imagsky.v6.domain.Member;
import com.imagsky.v7.domain.ContentFolder;
import java.util.Date;
import java.util.List;

/**
 *
 * @author jasonmak
 */
public class ContentFolderBiz extends V7AbstractBiz {

    public ContentFolderBiz(Member thisMember){
        super(thisMember);
    }
    public int totalCount() {
        ContentFolderDAO dao = ContentFolderDAO.getInstance();
        try {
            if (this.getParam("SEARCH_CF_NAME") != null) {
                ContentFolder cf = new ContentFolder();
                cf.setCF_NAME(this.getParam("SEARCH_CF_NAME")[0]);
                return dao.CNT_findTotalRecordCount(cf);
            } else {
                return dao.CNT_findTotalRecordCount();
            }
        } catch (Exception e) {
            this.addErrorMsg("ContentFolderBiz.totalCount() Exception: " + e.getMessage());
            cmaLogger.error("ContentFolderBiz.totalCount() Exception", e);
            return 0;
        }
    }

    public List<Object> list() {
        ContentFolderDAO dao = ContentFolderDAO.getInstance();
        int jtStartIndex = 0;
        int jtPageSize = 10;
        String jtSorting = " CF_NAME ASC";

        try {
            if (this.getParam("jtStartIndex") != null) {
                jtStartIndex = new Integer(this.getParam("jtStartIndex")[0]).intValue();
            }
            if (this.getParam("jtSorting") != null) {
                jtSorting = " " + this.getParam("jtSorting")[0];
            }
            if (this.getParam("jtPageSize") != null) {
                jtPageSize = new Integer(this.getParam("jtPageSize")[0]).intValue();
            }
            List<Object> list = null;
            if (this.getParam("SEARCH_CF_NAME") != null) {
                ContentFolder cf = new ContentFolder();
                cf.setCF_NAME(this.getParam("SEARCH_CF_NAME")[0]);
                list = dao.CNT_findListWithSample(cf, jtStartIndex, jtPageSize, JPAUtil.getOrderByString(jtSorting));
                cmaLogger.debug("Search by SearchValue");
            } else {
                list = dao.CNT_findAllByPage(jtStartIndex, jtPageSize, JPAUtil.getOrderByString(jtSorting));
                cmaLogger.debug("Search by all");
            }
            return list;
        } catch (Exception e) {
            this.addErrorMsg("ContentFolderBiz.list() Exception: " + e.getMessage());
            cmaLogger.error("ContentFolderBiz.list() Exception", e);
            return null;
        }
    }

    /**
     * *
     * Recurrive Add Content Folder
     *
     * @return
     */
    public ContentFolder create() {

        ContentFolder cf = new ContentFolder();
        ContentFolderDAO dao = ContentFolderDAO.getInstance();
        if (this.getParam("CF_NAME")[0].indexOf("/") > 0) {
            cf.setCF_NAME("/" + this.getParam("CF_NAME")[0]);
        } else {
            cf.setCF_NAME(this.getParam("CF_NAME")[0]);
        }
        if (cf.getCF_NAME().lastIndexOf("/") == cf.getCF_NAME().length() - 1) {
            cf.setCF_NAME(cf.getCF_NAME().substring(0, cf.getCF_NAME().length() - 2));
        }
        cf.setCF_DESC(this.getParam("CF_DESC")[0]);
        cf.setCF_OWNER("test");
        try {
            List<Object> list = dao.CNT_findListWithSample(cf);
            if (!CommonUtil.isNullOrEmpty(list)) {
                this.addErrorMsg("Folder Name is already existed: " + cf.getCF_NAME());
                return null;
            }
            String[] tokens = CommonUtil.stringTokenize(cf.getCF_NAME(), "/");

            if (tokens.length <= 5) {
                String tmpName = "";
                ContentFolder tmpEnq = new ContentFolder();
                for (int x = 0; x < tokens.length; x++) {
                    tmpName += "/" + tokens[x];
                    tmpEnq.setCF_NAME(tmpName);
                    list = dao.CNT_findListWithSample(tmpEnq);
                    if (list.isEmpty()) {
                        tmpEnq.setSys_guid(null);
                        if (x == tokens.length - 1) {
                            tmpEnq.setCF_DESC(cf.getCF_DESC());
                        } else {
                            tmpEnq.setCF_DESC("Generated by system.");
                        }
                        tmpEnq.setSys_cma_name("CF: " + tmpName);
                        tmpEnq.setCF_OWNER(cf.getCF_OWNER());
                        tmpEnq.setSys_create_dt(new Date());
                        tmpEnq.setSys_update_dt(new Date());
                        tmpEnq.setSys_is_live(Boolean.TRUE);
                        tmpEnq.setSys_is_node(Boolean.FALSE);
                        tmpEnq.setSys_is_published(Boolean.TRUE);
                        dao.CNT_create(tmpEnq);
                    }
                }
                list = dao.CNT_findListWithSample(cf);
                return (ContentFolder) list.get(0);
            } else {
                this.addErrorMsg("ContentFolderBiz.create() Exception: Folder name should be contained exceeding 5 levels.");
                return null;
            }
        } catch (Exception e) {
            this.addErrorMsg("ContentFolderBiz.create() Exception: " + cf.getCF_NAME() + " " + e.getMessage());
            cmaLogger.error("ContentFolderBiz.create() Exception", e);
            return null;
        }
    }

    public boolean delete() {
        ContentFolderDAO dao = ContentFolderDAO.getInstance();
        ContentFolder cf = new ContentFolder();

        if (this.getParam("sys_guid") == null) {
            this.addErrorMsg("Folder does not existed... ");
            return false;
        }
        try {
            cf.setSys_guid(this.getParam("sys_guid")[0]);
            dao.CNT_delete(cf);
            return true;
        } catch (Exception e) {
            this.addErrorMsg("ContentFolderBiz.delete() Exception: " + this.getParam("sys_guid")[0]);
            cmaLogger.error("ContentFolderBiz.delete() Exception", e);
            return false;
        }
    }

    /**
     * *
     * Control fields to be updated in this Business Class instead of DAO DAO
     * should be able to update most of the fields.
     *
     * @return
     */
    public ContentFolder update() {
        ContentFolderDAO dao = ContentFolderDAO.getInstance();
        ContentFolder cf = new ContentFolder();

        if (this.getParam("sys_guid") == null) {
            this.addErrorMsg("Folder does not existed... ");
            return null;
        }
        if (this.getParam("CF_DESC") == null) {
            this.addErrorMsg("Nothing needs to be updated... ");
            return null;
        }
        try {
            cf.setSys_guid(this.getParam("sys_guid")[0]);
            cf.setCF_DESC(this.getParam("CF_DESC")[0]);
            cf = (ContentFolder) dao.CNT_update(cf);
            return cf;
        } catch (Exception e) {
            this.addErrorMsg("ContentFolderBiz.update() Exception: " + this.getParam("sys_guid")[0]);
            cmaLogger.error("ContentFolderBiz.update() Exception", e);
            return null;
        }
    }
}
